# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MCMail.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MailMainWindow(object):
    def setupUi(self, MailMainWindow):
        MailMainWindow.setObjectName("MailMainWindow")
        MailMainWindow.resize(422, 462)
        MailMainWindow.setMinimumSize(QtCore.QSize(422, 462))
        MailMainWindow.setMaximumSize(QtCore.QSize(422, 462))
        MailMainWindow.setAutoFillBackground(False)
        MailMainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MailMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mensaje = QtWidgets.QTextEdit(self.centralwidget)
        self.mensaje.setGeometry(QtCore.QRect(13, 170, 401, 231))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mensaje.setFont(font)
        self.mensaje.setObjectName("mensaje")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(11, 11, 110, 34))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.subtitulo = QtWidgets.QLabel(self.centralwidget)
        self.subtitulo.setGeometry(QtCore.QRect(11, 51, 80, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.subtitulo.setFont(font)
        self.subtitulo.setObjectName("subtitulo")
        self.para = QtWidgets.QLineEdit(self.centralwidget)
        self.para.setGeometry(QtCore.QRect(92, 96, 321, 20))
        self.para.setObjectName("para")
        self.para_tag = QtWidgets.QLabel(self.centralwidget)
        self.para_tag.setGeometry(QtCore.QRect(11, 96, 37, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.para_tag.setFont(font)
        self.para_tag.setObjectName("para_tag")
        self.prioridad = QtWidgets.QCheckBox(self.centralwidget)
        self.prioridad.setGeometry(QtCore.QRect(11, 410, 120, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prioridad.setFont(font)
        self.prioridad.setChecked(False)
        self.prioridad.setObjectName("prioridad")
        self.enviar = QtWidgets.QPushButton(self.centralwidget)
        self.enviar.setGeometry(QtCore.QRect(337, 410, 75, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.enviar.setFont(font)
        self.enviar.setObjectName("enviar")
        self.asunto = QtWidgets.QLineEdit(self.centralwidget)
        self.asunto.setGeometry(QtCore.QRect(92, 122, 171, 20))
        self.asunto.setObjectName("asunto")
        self.de_tag = QtWidgets.QLabel(self.centralwidget)
        self.de_tag.setGeometry(QtCore.QRect(11, 70, 25, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.de_tag.setFont(font)
        self.de_tag.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.de_tag.setFrameShadow(QtWidgets.QFrame.Plain)
        self.de_tag.setLineWidth(0)
        self.de_tag.setObjectName("de_tag")
        self.de = QtWidgets.QLineEdit(self.centralwidget)
        self.de.setGeometry(QtCore.QRect(92, 70, 321, 20))
        self.de.setReadOnly(True)
        self.de.setObjectName("de")
        self.asunto_tag = QtWidgets.QLabel(self.centralwidget)
        self.asunto_tag.setGeometry(QtCore.QRect(11, 122, 56, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.asunto_tag.setFont(font)
        self.asunto_tag.setObjectName("asunto_tag")
        self.mensaje_tag = QtWidgets.QLabel(self.centralwidget)
        self.mensaje_tag.setGeometry(QtCore.QRect(11, 148, 63, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mensaje_tag.setFont(font)
        self.mensaje_tag.setObjectName("mensaje_tag")
        MailMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MailMainWindow)
        self.statusbar.setObjectName("statusbar")
        MailMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MailMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MailMainWindow)

    def retranslateUi(self, MailMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MailMainWindow.setWindowTitle(_translate("MailMainWindow", "MC Mail"))
        self.mensaje.setHtml(_translate("MailMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"></span></p></body></html>"))
        self.titulo.setText(_translate("MailMainWindow", "MC Mail"))
        self.subtitulo.setText(_translate("MailMainWindow", "por @MContenla"))
        self.para_tag.setText(_translate("MailMainWindow", "Para:"))
        self.prioridad.setText(_translate("MailMainWindow", "Alta prioridad"))
        self.enviar.setText(_translate("MailMainWindow", "Enviar"))
        self.de_tag.setText(_translate("MailMainWindow", "De:"))
        self.asunto_tag.setText(_translate("MailMainWindow", "Asunto:"))
        self.mensaje_tag.setText(_translate("MailMainWindow", "Mensaje:"))
